object Versions {
    const val ANDROIDX_CORE = "1.7.0"
    const val APPCOMPAT = "1.3.1"
    const val ANDROIDX_LEGACY_SUPPORT = "1.0.0"
    const val NAVIGATION_COMPONENT = "2.4.0"
    const val CONSTRAINT_LAYOUT = "2.1.2"
    const val DATASTORE_PREFERENCES = "1.0.0"
    const val PAGING = "3.1.0"
    const val LIFECYCLE_COROUTINE = "2.4.0"
    const val GLIDE = "4.12.0"
    const val GLIDE_COMPILER = "4.12.0"
    const val DAGGER_HILT = "2.40.5"
    const val RETROFIT2 = "2.9.0"
    const val GSON_CONVERTER = "2.9.0"
    const val GSON = "2.8.7"
    const val LOGGING_INTERCEPTOR = "4.9.2"
    const val FRAGMENT_KTX = "1.4.0"
    const val RECYCLERVIEW = "1.2.1"
    const val VIEWMODEL_SAVEDSTATE = "2.4.0"
    const val MATERIAL_DESIGN = "1.4.0"
    const val LEAK_CANARY = "2.7"
    const val DOTSINDICATOR = "4.2"
    const val CIRCLE_IMAGEVIEW = "3.1.0"
    const val KTLINT_VERSION = "10.2.0"
    const val TOOLS_BUILD_GRADLE = "7.0.4"
    const val KOTLIN_GRADLE_PLUGIN = "1.6.10"
    const val LOTTIE_ANIMATION = "3.4.0"
    const val GOOGLE_SERVICE = "4.3.10"
    const val FIREBASE_BOM = "29.0.4"
    const val FIREBASE_CRASHLYTICS_GRADLE = "2.8.1"
    const val FIREBASE_CLOUD_MESSAGING = "23.0.0"
    const val ROOM = "2.4.1"
    const val ROOM_PAGING = "2.5.0-alpha01"
    const val SWIPE_REFRESH="1.1.0"

    //test
    const val JUNIT = "4.13.1"
    const val EXT_JUNIT = "1.1.3"
    const val ESPRESSO_CORE = "3.4.0"
}